// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AtualizarVeiculo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AtualizarVeiculo'](arg1, arg2, arg3, arg4);
}

export function CriarVeiculo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CriarVeiculo'](arg1, arg2, arg3);
}

export function DashboardCompleto(arg1, arg2) {
  return window['go']['main']['App']['DashboardCompleto'](arg1, arg2);
}

export function DashboardDiario(arg1) {
  return window['go']['main']['App']['DashboardDiario'](arg1);
}

export function ExcluirVeiculo(arg1) {
  return window['go']['main']['App']['ExcluirVeiculo'](arg1);
}

export function LimparTodosRegistros() {
  return window['go']['main']['App']['LimparTodosRegistros']();
}

export function ListarCategorias() {
  return window['go']['main']['App']['ListarCategorias']();
}

export function ListarRegistrosParciaisPorData(arg1) {
  return window['go']['main']['App']['ListarRegistrosParciaisPorData'](arg1);
}

export function ListarRegistrosParciaisPorPeriodo(arg1, arg2) {
  return window['go']['main']['App']['ListarRegistrosParciaisPorPeriodo'](arg1, arg2);
}

export function ListarTiposOcorrencia() {
  return window['go']['main']['App']['ListarTiposOcorrencia']();
}

export function ListarVeiculos() {
  return window['go']['main']['App']['ListarVeiculos']();
}

export function SalvarRegistrosParciais(arg1, arg2) {
  return window['go']['main']['App']['SalvarRegistrosParciais'](arg1, arg2);
}
