// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AtualizarRegistro(arg1, arg2) {
  return window['go']['main']['App']['AtualizarRegistro'](arg1, arg2);
}

export function AtualizarVeiculo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AtualizarVeiculo'](arg1, arg2, arg3, arg4);
}

export function CriarRegistro(arg1) {
  return window['go']['main']['App']['CriarRegistro'](arg1);
}

export function CriarVeiculo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CriarVeiculo'](arg1, arg2, arg3);
}

export function DashboardDiario(arg1) {
  return window['go']['main']['App']['DashboardDiario'](arg1);
}

export function DashboardMensal(arg1, arg2) {
  return window['go']['main']['App']['DashboardMensal'](arg1, arg2);
}

export function ExcluirRegistro(arg1) {
  return window['go']['main']['App']['ExcluirRegistro'](arg1);
}

export function ExcluirVeiculo(arg1) {
  return window['go']['main']['App']['ExcluirVeiculo'](arg1);
}

export function ListarCategorias() {
  return window['go']['main']['App']['ListarCategorias']();
}

export function ListarRegistros() {
  return window['go']['main']['App']['ListarRegistros']();
}

export function ListarVeiculos() {
  return window['go']['main']['App']['ListarVeiculos']();
}
