// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AtualizarVeiculo(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function CriarVeiculo(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DashboardCompleto(arg1:number,arg2:number):Promise<main.DashboardResponse>;

export function DashboardDiario(arg1:string):Promise<main.DashboardResponse>;

export function ExcluirVeiculo(arg1:number):Promise<Record<string, any>>;

export function LimparTodosRegistros():Promise<Record<string, any>>;

export function ListarCategorias():Promise<Array<main.Categoria>>;

export function ListarRegistrosParciaisPorData(arg1:string):Promise<Array<Record<string, any>>>;

export function ListarRegistrosParciaisPorPeriodo(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ListarTiposOcorrencia():Promise<Array<string>>;

export function ListarVeiculos():Promise<Array<Record<string, any>>>;

export function SalvarRegistrosParciais(arg1:string,arg2:Array<main.RegistroParcialPayload>):Promise<Record<string, any>>;
