// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AtualizarRegistro(arg1:number,arg2:main.RegistroPayload):Promise<Record<string, any>>;

export function AtualizarVeiculo(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function CriarRegistro(arg1:main.RegistroPayload):Promise<Record<string, any>>;

export function CriarVeiculo(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DashboardDiario(arg1:string):Promise<main.DashboardResponse>;

export function DashboardMensal(arg1:number,arg2:number):Promise<main.DashboardResponse>;

export function ExcluirRegistro(arg1:number):Promise<Record<string, any>>;

export function ExcluirVeiculo(arg1:number):Promise<Record<string, any>>;

export function ListarCategorias():Promise<Array<main.Categoria>>;

export function ListarRegistros():Promise<Array<Record<string, any>>>;

export function ListarVeiculos():Promise<Array<Record<string, any>>>;
